#!/bin/sh
. /usr/share/htmlscript/helpers

if rpm -q cups &>/dev/null; then
	kcmshell kcm_printer_manager
else
	APP=$"Task printing-scanning"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes task-printing task-printing-scanning print-manager system-config-printer
	ProgressDialog --close
	if rpm -q cups &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi

exit 0
