#!/bin/bash
. /usr/share/htmlscript/helpers

if rpm -q lutris; then
	kdialog --title $"OpenMandriva"  --msgbox  $" lutris is already installed."
else
	APP=$"Lutris"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes lutris
	ProgressDialog --close
	if rpm -q lutris; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
