#!/bin/bash
. /usr/share/htmlscript/helpers
if which zim; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Zim Wiki Editor is already installed."
else
	APP=$"Zim Wiki Editor"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes zim
	ProgressDialog --close
	if which zim; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
