#!/bin/bash
. /usr/share/htmlscript/helpers
if which puzzle-jigsaw &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Puzzle jigsaw is already installed."
else
	APP=$"Puzzle jigsaw"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes puzzle-jigsaw
	ProgressDialog --close
	if which puzzle-jigsaw &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
