#!/bin/bash
if which qtcreator; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" Qt-Creator is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes qt-creator
	if which qtcreator; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Qt-Creator successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Qt-Creator not installed."
	fi
fi
