#!/bin/bash
. /usr/share/htmlscript/helpers
if which choqok; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Choqok is already installed."
else
	APP=$"Choqok"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes choqok
	ProgressDialog --close
	if which choqok; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
