#!/bin/bash

if which grsync; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" GRsync is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	enable-repo unsupported
	pkexec dnf install --assumeyes grsync
	if which grsync; then
		kdialog --title $"OpenMandriva"  --msgbox  $" GRsync successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" GRsync not installed."
	fi
fi
