#!/bin/bash

if which eclipse; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" Eclipse IDE is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes eclipse-platform
	if which eclipse; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Eclipse IDE successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Eclipse IDE not installed."
	fi
fi
