#!/bin/bash
. /usr/share/htmlscript/helpers
if which audacity; then
	kdialog --title $"OpenMandriva" --msgbox $" Audacity is already installed.";
else
	APP=$"Audacity"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes audacity
	ProgressDialog --close
	if which audacity; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
