#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -qa |grep "calibre*"; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Calibre is already installed."
else
	APP=$"Calibre"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes calibre
	ProgressDialog --close
	if rpm -q calibre; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
