#!/bin/bash
. /usr/share/htmlscript/helpers
if which step &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Step is already installed."
else
	APP=$"Step"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes step
	ProgressDialog --close
	if which step &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
