#!/bin/bash
. /usr/share/htmlscript/helpers
if which firefox &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Firefox is already installed."
else
	APP=$"Firefox"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes firefox
	ProgressDialog --close
	if which firefox &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
