#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q tuxpaint; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Tux Paint is already installed."
else
	APP=$"Tux Paint"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes tuxpaint tuxpaint-stamps
	ProgressDialog --close
	if rpm -q tuxpaint; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
