#!/bin/bash
. /usr/share/htmlscript/helpers
if which stacer &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Stacer is already installed."
else
	APP=$"Stacer"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes stacer
	ProgressDialog --close
	if which stacer &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
