#!/bin/bash
. /usr/share/htmlscript/helpers
if which endless-sky &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Endless Sky is already installed."
else
	APP=$"Endless Sky"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes endless-sky
	ProgressDialog --close
	if which endless-sky &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
