#!/bin/bash
. /usr/share/htmlscript/helpers

if rpm -qa |grep "^gimp"; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Gimp is already installed."
else
	APP=$"GIMP"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes gimp
	ProgressDialog --close
	if rpm -qa |grep "^gimp"; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
