#!/bin/bash
if which rosa-media-player; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" ROSA Media Player is already installed."
else 
	kdesu -- dnf install --assumeyes rosa-media-player
	if which rosa-media-player; then
		kdialog --title $"OpenMandriva"  --msgbox  $" ROSA Media Player successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" ROSA Media Playernot installed."
	fi
fi
