#!/bin/bash
. /usr/share/htmlscript/helpers

if which filezilla; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Filezilla is already installed."
else
	APP=$"Filezilla"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes filezilla
	ProgressDialog --close
	if which filezilla; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
