#!/bin/bash
. /usr/share/htmlscript/helpers
if which nheko &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"nheko is already installed."
else
	APP=$"Nheko"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes nheko
	ProgressDialog --close
	if which nheko &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
