#!/bin/bash
. /usr/share/htmlscript/helpers
if which handbrake; then
	kdialog --title $"OpenMandriva"  --msgbox  $" HandBrake is already installed."
else
	APP=$"HandBrake"
	ProgressDialog $"Installing $APP"
	enable-repo restricted
	pkexec dnf install --assumeyes handbrake
	ProgressDialog --close
	if which handbrake; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
