#!/bin/bash
if which kalzium &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Kalzium is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes kalzium
	if which kalzium &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
