#!/bin/bash
. /usr/share/htmlscript/helpers
if which designer; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Qt5-Designer is already installed."
else
	APP=$"Qt Designer"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes qt5-designer
	ProgressDialog --close
	if which designer; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
