#!/bin/bash
. /usr/share/htmlscript/helpers
if which pixelize &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Pixelize is already installed."
else
	APP=$"Pixelize"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes pixelize
	ProgressDialog --close
	if which pixelize &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
