#!/bin/bash

if which homebank; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" Homebank is already installed.";
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes homebank
	if which homebank; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Homebank successfully installed.";
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Homebank not installed.";
	fi
fi
