#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q wesnoth; then
	kdialog --title $"OpenMandriva"  --msgbox  $" wesnoth is already installed."
else
	APP=$"Wesnoth"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes wesnoth
	ProgressDialog --close
	if rpm -q wesnoth; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
