#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q supertux &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Supertux is already installed."
else
	APP=$"Super Tux"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes supertux
	ProgressDialog --close
	if rpm -q supertux &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
