#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q torcs; then
	kdialog --title $"OpenMandriva"  --msgbox  $" torcs is already installed."
else
	APP=$"Torcs"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes torcs
	ProgressDialog --close
	if rpm -q torcs; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
