#!/bin/bash
. /usr/share/htmlscript/helpers
if which geany; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Geany IDE is already installed."
else
	APP=$"Geany IDE"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes geany
	ProgressDialog --close
	if which geany; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
