#!/bin/bash
. /usr/share/htmlscript/helpers
if which falkon &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Falkon is already installed."
else
	APP=$"Falkon"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes falkon
	ProgressDialog --close
	if which falkon &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
