#!/bin/bash
. /usr/share/htmlscript/helpers
if which artikulate &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Artikulate is already installed."
else
	APP=$"Artikulate"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes artikulate
	ProgressDialog --close
	if which artikulate &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
