#!/bin/sh
. /usr/share/htmlscript/helpers
if rpm -q dnfdrake &>/dev/null; then
	exec dnfdrake.gambas
else
	APP=$"DnfDrake"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes dnfdrake
	ProgressDialog --close
	if rpm -q dnfdrake &>/dev/null; then
		kdialog --title $"OpenMandriva"  --msgbox  $" DnfDrake successfully installed."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi

exit 0
