#!/bin/bash
if which clang &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" LLVM/clang is already installed."
else
	pkexec dnf install --assumeyes task-devel task-c-devel task-c++-devel clang llvm
	if which clang &>/dev/null; then
		kdialog --title $"OpenMandriva"  --msgbox  $" LLVM/clang successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" LLVM/clang not installed."
	fi
fi
