#!/bin/bash
. /usr/share/htmlscript/helpers
if which smplayer; then
	kdialog --title $"OpenMandriva"  --msgbox  $" SMPlayer is already installed."
else
	APP=$"SMPlayer"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes smplayer
	ProgressDialog --close
	if which smplayer; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
