#!/bin/bash
. /usr/share/htmlscript/helpers
if which tuxpusher &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"TuxPusher is already installed."
else
	APP=$"TuxPusher"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes tuxpusher
	ProgressDialog --close
	if which tuxpusher &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
