#!/bin/bash
. /usr/share/htmlscript/helpers
if which chromium; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Chromium Webbrowser is already installed."
else
	APP=$"Chromium"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes chromium
	ProgressDialog --close
	if which chromium; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
