#!/bin/bash
. /usr/share/htmlscript/helpers

if rpm -q inkscape; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Inkscape is already installed."
else
	APP=$"Inkscape"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes inkscape
	ProgressDialog --close
	if rpm -q inkscape; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
