#!/bin/bash
if rpm -qa |grep "nautilus-dropbox*"; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" nautilus-dropbox (Dropbox extension) is already installed."
else 
	kdesu -- dnf install --assumeyes nautilus-dropbox
	if rpm -qa |grep "nautilus-dropbox*"; then
		kdialog --title $"OpenMandriva"  --msgbox  $" nautilus-dropbox (Dropbox extension) successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" nautilus-dropbox (Dropbox extension) not installed."
	fi
fi
