#!/bin/bash
. /usr/share/htmlscript/helpers

if which fotoxx; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Fotoxx is already installed."
else
	APP=$"Fotoxx"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes fotoxx
	ProgressDialog --close
	if which fotoxx; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
