#!/bin/bash
. /usr/share/htmlscript/helpers
if which obs &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"OBS Studio is already installed."
else
	APP=$"Open Broadcast Studio"
	ProgressDialog $"Installing $APP"
	enable-repo restricted
	pkexec dnf install --assumeyes obs-studio
	ProgressDialog --close
	if which obs &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
