#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -qa |grep "xvidcap*"; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Xvidcap is already installed."
else
	APP=$"XVidCap"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes xvidcap
	ProgressDialog --close
	if which xvidcap; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
