#!/bin/bash
. /usr/share/htmlscript/helpers

if which eclipse; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Eclipse IDE is already installed."
else
	APP=$"Eclipse"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes eclipse-platform
	ProgressDialog --close
	if which eclipse; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
