#!/bin/bash
. /usr/share/htmlscript/helpers
if which pidgin; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Pidgin Internet Messenger is already installed."
else
	APP=$"Pidgin Internet Messenger"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes pidgin
	ProgressDialog --close
	if which pidgin; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
