#!/bin/bash
. /usr/share/htmlscript/helpers
if which thunderbird; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Mozilla Thunderbird is already installed."
else
	APP=$"Thunderbird"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes thunderbird
	ProgressDialog --close
	if which thunderbird; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
