#!/bin/bash
. /usr/share/htmlscript/helpers
if which dupeguru &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"dupeGuru is already installed."
else
	APP=$"Dupeguru"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes dupeguru
	ProgressDialog --close
	if which dupeguru &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
