#!/bin/bash

if rpm -q lutris; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" lutris is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes lutris
	if rpm -q lutris; then
		kdialog --title $"OpenMandriva"  --msgbox  $" lutris successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" lutris not installed."
	fi
fi
