#!/bin/bash
. /usr/share/htmlscript/helpers

if which homebank; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Homebank is already installed.";
else
	APP=$"Homebank"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes homebank
	ProgressDialog --close
	if which homebank; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
