#!/bin/bash
. /usr/share/htmlscript/helpers
if which quaternion &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Quaternion is already installed."
else
	APP=$"Quaternion"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes quaternion
	ProgressDialog --close
	if which quaternion &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
