#!/bin/bash
. /usr/share/htmlscript/helpers
if which telegram-desktop &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"telegram-desktop is already installed."
else
	APP=$"Telegram"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes telegram-desktop
	ProgressDialog --close
	if which telegram-desktop &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
