#!/bin/bash
. /usr/share/htmlscript/helpers
if which quassel &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Quassel is already installed."
else
	APP=$"Quassel"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes quassel
	ProgressDialog --close
	if which quassel &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
