#!/bin/bash
. /usr/share/htmlscript/helpers
if which gcompris-qt &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"GCompris is already installed."
else
	APP=$"GCompris Qt"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes gcompris-qt
	ProgressDialog --close
	if which gcompris-qt &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
