#!/bin/bash
. /usr/share/htmlscript/helpers
if which cantor &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Cantor is already installed."
else
	APP=$"Cantor"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes cantor
	ProgressDialog --close
	if which cantor &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
