#!/bin/bash

if which filezilla; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" Filezilla is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes filezilla
	if which filezilla; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Filezilla successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Filezilla not installed."
	fi
fi
