#!/bin/bash
. /usr/share/htmlscript/helpers
if which haruna &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"haruna is already installed."
else
	APP=$"Haruna"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes haruna
	ProgressDialog --close
	if which haruna &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
