#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q scratch &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Scratch is already installed."
else
	APP=$"Scratch"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes scratch
	ProgressDialog --close
	if rpm -q scratch &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
