#!/bin/bash
. /usr/share/htmlscript/helpers
if which nulloy &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"nulloy is already installed."
else
	APP=$"Nulloy"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes nulloy
	ProgressDialog --close
	if which nulloy &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
