#!/bin/bash
. /usr/share/htmlscript/helpers
if which supertuxkart &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"SuperTuxKart is already installed."
else
	APP=$"SuperTuxKart"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes supertuxkart
	ProgressDialog --close
	if which supertuxkart &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
