#!/bin/bash
. /usr/share/htmlscript/helpers
if which etr &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Extreme Tux Racer is already installed."
else
	APP=$"Extreme Tux Racer"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes etr
	ProgressDialog --close
	if which etr &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
