#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q unar; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Unar is already installed."
else
	APP=$"Unar"
	ProgressDialog $"Installing $APP"
	enable-repo non-free
	pkexec dnf install --assumeyes unar zip p7zip ncompress
	ProgressDialog --close
	if which unar; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
