#!/bin/bash
. /usr/share/htmlscript/helpers
if which vlc &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"VLC is already installed."
else
	APP=$"VLC"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes vlc
	ProgressDialog --close
	if which vlc &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
