#!/bin/bash
. /usr/share/htmlscript/helpers
if which rocs &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Rocs is already installed."
else
	APP=$"Rocs"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes rocs
	ProgressDialog --close
	if which rocs &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
