#!/bin/bash
. /usr/share/htmlscript/helpers
if which kaudiocreator; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Kaudiocreator is already installed."
else
	APP=$"KAudioCreator"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes kaudiocreator
	ProgressDialog --close
	if which kaudiocreator; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
