#!/bin/bash
. /usr/share/htmlscript/helpers
if which kdevelop; then
	kdialog --title $"OpenMandriva"  --msgbox  $" KDevelop is already installed."
else
	APP=$"KDevelop"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes kdevelop
	ProgressDialog --close
	if which kdevelop; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
