#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q virtualbox &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Virtualbox is already installed."
else
	APP=$"VirtualBox"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes virtualbox
	ProgressDialog --close
	if rpm -q virtualbox &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
