#!/bin/bash
. /usr/share/htmlscript/helpers
if which musescore &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"MuseScore is already installed."
else
	APP=$"MuseScore"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes musescore
	ProgressDialog --close
	if which musescore &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
