#!/bin/bash
if rpm -q warzone2100 &>/dev/null; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" Warzone 2100 game is already installed."
else 
	pkexec dnf install --assumeyes warzone2100
	if rpm -q warzone2100 &>/dev/null; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Warzone 2100 game successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Warzone 2100 game not installed."
	fi
fi
