#!/bin/bash
. /usr/share/htmlscript/helpers
if which kstars &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"KStars is already installed."
else
	APP=$"KStars"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes kstars
	ProgressDialog --close
	if which kstars &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
