#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q get-skypeforlinux; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Skype is already installed."
else
	APP=$"Skype"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes get-skypeforlinux
	ProgressDialog --close
	if rpm -q get-skypeforlinux; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
