#!/bin/bash
if rpm -q wesnoth; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" wesnoth is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes wesnoth
	if rpm -q wesnoth; then
		kdialog --title $"OpenMandriva"  --msgbox  $" wesnoth successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" wesnoth not installed."
	fi
fi
