#!/bin/bash
. /usr/share/htmlscript/helpers
if which strawberry &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"strawberry is already installed."
else
	APP=$"Strawberry"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes strawberry
	ProgressDialog --close
	if which strawberry &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
