#!/bin/bash
. /usr/share/htmlscript/helpers
if rpm -q calligra &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Calligra Office Suite is already installed."
else
	APP=$"Calligra"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes calligra*
	ProgressDialog --close
	if rpm -q calligra &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
