#!/bin/bash

if rpm -q scribus; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" Scribus is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes scribus
	if rpm -q scribus; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Scribus successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $"Scribus not installed."
	fi
fi
