#!/bin/bash
. /usr/share/htmlscript/helpers
if which wine; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Wine is already installed."
else
	APP=$"Wine"
	ProgressDialog $"Installing $APP"
	pkexec dnf --refresh install --assumeyes wine cabextract
	ProgressDialog --close
	if which wine; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
