#!/bin/bash
. /usr/share/htmlscript/helpers
if which bottles &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"Bottles is already installed."
else
	APP=$"Bottles"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes bottles
	ProgressDialog --close
	if which bottles &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
