#!/bin/bash
if rpm -q torcs; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" torcs is already installed."
else 
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	enable-repo unsupported
	pkexec dnf install --assumeyes torcs
	if rpm -q torcs; then
		kdialog --title $"OpenMandriva"  --msgbox  $" torcs successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" torcs not installed."
	fi
fi
