#!/bin/bash
if which audacity; then 
	kdialog --title $"OpenMandriva" --msgbox $" Audacity is already installed.";
else
kdialog --title $"OpenMandriva" --msgbox $"Work in progress, please wait until the process is done, it may take a while"
	pkexec dnf install --assumeyes audacity
	if which audacity; then
		kdialog --title $"OpenMandriva" --msgbox $" Audacity successfully installed."
	else
		kdialog --title $"OpenMandriva" --msgbox $" Audacity not installed."
	fi
fi
