#!/bin/bash
. /usr/share/htmlscript/helpers
if which babe &>/dev/null; then
	kdialog --title $"OpenMandriva" --msgbox $"babe is already installed."
else
	APP=$"Babe"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes babe
	ProgressDialog --close
	if which babe &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
