#!/bin/bash
. /usr/share/htmlscript/helpers

if which qmmp; then
	kdialog --title $"OpenMandriva"  --msgbox  $" QMMP is already installed."
else
	APP=$"QMMP"
	ProgressDialog $"Installing $APP"
	enable-repo unsupported
	pkexec dnf install --assumeyes qmmp
	ProgressDialog --close
	if which qmmp; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi
