#!/bin/sh
. /usr/share/htmlscript/helpers
if rpm -q om-feeling-like &>/dev/null; then
	exec om-feeling-like-ui
else
	APP=$"Desktop Presets"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes om-feeling-like
	ProgressDialog --close
	if rpm -q om-feeling-like &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi

exit 0
