#!/bin/sh
. /usr/share/htmlscript/helpers
if rpm -q om-update-config &>/dev/null; then
	exec om-update-config-ui
else
	APP=$"Update Configuration"
	ProgressDialog $"Installing $APP"
	pkexec dnf install --assumeyes om-update-config
	ProgressDialog --close
	if rpm -q om-update-config &>/dev/null; then
		kdialog --title $"OpenMandriva" --msgbox $"Installation succeeded."
	else
		kdialog --title $"OpenMandriva" --msgbox $"Installation failed."
	fi
fi

exit 0
