#!/bin/bash
if which pidgin; then 
	kdialog --title $"OpenMandriva"  --msgbox  $" Pidgin Internet Messenger is already installed."
else
	pkexec dnf install --assumeyes pidgin
	if which pidgin; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Pidgin Internet Messenger successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Pidgin Internet Messenger not installed."
	fi
fi
